/**
 * Implementation Layer 
 * The implementation layer is home to a wide array of ways you can call apex across the Salesforce platform. 
 * The most basic implementation layer is an Apex Controller. 
 * A Controller is home to methods that expose the Service layers methods and business logic. 
 * Controllers may interact with multiple Service classes but should hold only very minimal logic.
 */
public interface IController {
    
}